<?php
    echo'<footer>
        <p>Created by The Debuggers:</p>
        <p><a href="mailto:103990049@student.swin.edu.au">Jude Gualano</a></p>
        <p><a href="mailto:103981441@student.swin.edu.au">Camille Louis-Abeysinghe</a></p>
        <p><a href="mailto:103058400@student.swin.edu.au">Matthew Falcke</a></p>
        <p><a href="mailto:103523995@student.swin.edu.au">Sadman Sakhi Sachcha</a></p>
        <p><a href="mailto:103838767@student.swin.edu.au">Sadikin Ahmed Seam</a></p>
    </footer>';
?>