<?php
    echo'<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="style.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Francois+One&family=Jura:wght@600&family=Merriweather&family=Rubik:wght@400;500&family=Source+Sans+Pro:ital,wght@0,400;1,300;1,400&display=swap" rel="stylesheet"><meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="style.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Francois+One&family=Jura:wght@600&family=Merriweather&family=Rubik:wght@400;500&family=Source+Sans+Pro:ital,wght@0,400;1,300;1,400&display=swap" rel="stylesheet">';
?>